
CREATE TABLE `t_config_month_standard` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `type` varchar(100) NOT NULL COMMENT '数据类型',
  `year` int(11) NOT NULL COMMENT '年份',
  `season` varchar(10) DEFAULT '' COMMENT '系列',
  `month` int(11) NOT NULL COMMENT '月份',
  `week` int(11) DEFAULT NULL COMMENT '周',
  `order_no` varchar(10) DEFAULT '' COMMENT '单号',
  `plan_level` varchar(10) DEFAULT '' COMMENT '企划等级',
  `sale_level` varchar(10) DEFAULT '' COMMENT '销售级别',
  `brand` varchar(10) DEFAULT '' COMMENT '品牌',
  `serial` varchar(10) DEFAULT '' COMMENT '系列',
  `original_serial` varchar(10) DEFAULT '' COMMENT '原系列',
  `design_grouping` varchar(10) DEFAULT NULL COMMENT '设计分组',
  `style` varchar(10) DEFAULT '' COMMENT '风格',
  `goods_level` varchar(10) DEFAULT '' COMMENT '商品层',
  `category` varchar(10) DEFAULT '' COMMENT '品类',
  `area` varchar(10) DEFAULT NULL COMMENT '大区',
  `sub_category` varchar(10) DEFAULT '' COMMENT '中品类',
  `plan_shop_no` varchar(50) DEFAULT '' COMMENT '企划店铺编码',
  `shop_no` varchar(20) DEFAULT NULL COMMENT '店铺编码',
  `std_value` decimal(10,2) DEFAULT NULL COMMENT '标准值',
  `std_max_value` decimal(10,2) DEFAULT NULL COMMENT '标准值上限',
  `std_min_value` decimal(10,2) DEFAULT NULL COMMENT '标准值下限',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `create_by` varchar(50) NOT NULL COMMENT '创建者',
  `modify_time` datetime NOT NULL COMMENT '修改时间',
  `modify_by` varchar(50) NOT NULL COMMENT '修改者',
  PRIMARY KEY (`id`),
  KEY `Index_1` (`type`) USING BTREE,
  KEY `Index_2` (`year`) USING BTREE,
  KEY `Index_3` (`month`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=78382 DEFAULT CHARSET=utf8 COMMENT='bi月度标准值配置'