server:
  port: 9093
  servlet:
    context-path: /
    session:
      cookie:
        name: sessionid_p

###配置eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.ur.com.cn:9292/eureka/
    #是否注册
    registerWithEureka: false 
  ###配置客户端hostname,statusPageUrlPath为swagger-ui,方便查看接口api
  instance:
    hostname: ims.ur.com.cn
spring:
  servlet:
    multipart:
      ##单个数据大小 
      maxFileSize: 5MB
      ##总数据大小
      maxRequestSize: 5MB
  zipkin:
    #base-url: http://eureka.ur.com.cn:9292
    base-url: http://10.2.16.21:9292
  sleuth:
    sampler:
      ##zipkin采样率，默认为0.1，改为1后全采样，但是会降低接口调用效率
      percentage: 0.1
      #probability: 1.0
  datasource:    
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 100
      maxAge: 30000
      #最大空闲时间，30s未使用，则被丢弃
      maxIdleTime: 30
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select '1'
      testWhileIdle: true
      #对数据库连接的有效性进行了验证
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true    
      username: druid  
      password: 123456              
        
      imms-connection:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.15.143:3306/ur_imms?useUnicode=true&characterEncoding=UTF-8
        username: usr_imms_admin  
        password: Gaole1xiaoShi   
      hk-connection:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  
        url:  jdbc:sqlserver://ur-mssql02.ur.com.cn;DatabaseName=HKERP
        username: IMS_HK_WRITE
        password: "urIMStoHK#4321"
      oamiddle-connection:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  
        url: jdbc:sqlserver://lsn-ur-scm.ur.com.cn:2433;DatabaseName=OA_MIDDLE  
        username: IMS_SCM_WRITE  
        password: "urIMSSCM#1200"
      #scm中间表
      middleware-connection:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  
        url: jdbc:sqlserver://lsn-ur-scm.ur.com.cn:2433;DatabaseName=middleware   
        username: IMS_SCM_WRITE  
        password: "urIMSSCM#1200"
      scm-connection:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  
        url: jdbc:sqlserver://lsn-ur-scm.ur.com.cn:2433;DatabaseName=nqr   
        username: IMS_SCM_WRITE  
        password: "urIMSSCM#1200"
      scmread-connection:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  
        url: jdbc:sqlserver://lsn-ur-scm.ur.com.cn:2433;DatabaseName=nqr   
        username: IMS_SCM_WRITE  
        password: "urIMSSCM#1200"
        
  redis:
    #redisKey前缀，用于区分信息来自那个系统
    redisKeyPrefix: IMS-PLAN
    #Redis数据库索引（默认为0）
    database: 0   
    #Redis服务器地址
    host: 10.2.16.23
    #Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000
   
  #rabbitmq连接参数
#  rabbitmq:
#    imsMq:
#      enabled: true
#      enabled-listener: false
#      host: mqserver03-vp.ur.com.cn
#      port: 5672
#      username: ims_user
#      password: abc,123
#      virtual-host: plan-host
#      #rabbitmq消息确认
#      publisher-confirms: true
#      publisher-returns: true
        
logging:
  level:
    com.ur: info    
cas:
  server:
    host:
      url: http://cas.ur.com.cn:8787/cas            #CAS服务地址  
      login_url: ${cas.server.host.url}/login   #CAS服务登录地址  
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}        #CAS服务登出地址 
  
app:
  server:
    host:
      url: http://${eureka.instance.hostname}:${server.port}         #应用访问地址
  login:
    url: /login                          #应用登录地址
  logout:
    url: /logout                         #应用登出地址    

  #tempFilePath: D:\workspace\workspace_portal\URFrameworkTemplate\
  tempFilePath: /tmp
  seperator:   
  exportPageSize: 50000    
pic:
  server:
    host:
      #scm服务地址
      url: http://pic.ur.com.cn/admin 
      #scm文件上传地址
      upload_url: ${pic.server.host.url}/sys/files/upload
      #scm文件下载地址
      download_url: ${pic.server.host.url}/sys/file/download
      #图片浏览地址，根据abbfilename
      image_url: ${pic.server.host.url}/sys/file/image/
      #http://pic.ur.com.cn/admin/sys/file/cyImageZ/19SY200129_L
      cyImageZ_url: ${pic.server.host.url}/sys/file/cyImageZ/


  #店铺主数据同步oa
shop:
  accessKey: 4D8DB5B5DF89CF158D8CDEFBE49079FFAB
  accessSecret: DD5D13A28E2A17BBBE8393EA52E36ABAFF
  tokenUrl: http://10.0.17.223:8080/api/accesstoken/get_token
  employUrl: http://10.0.17.223:8080/api/hrm/staffGet
  storeInfoUrl: http://10.0.17.223:8080/api/slm/storeInfoGet

sap:
  interfaces: open
  username: SLMTOPI
  password: 123456Aa
  url: http://sappod01.ur.com.cn:50100/XISOAPAdapter/MessageServlet
  url1: ${sap.url}?senderParty=&senderService=SLM_Q&receiverParty=&receiverService=&interface=SLM_MasterData_Out&interfaceNamespace=urn%3Aur.cn%3ASLM%3AERP%3AMasterData
  url2: ${sap.url}?senderParty=&senderService=SLM_Q&receiverParty=&receiverService=&interface=SLM_BusinessData_Out&interfaceNamespace=urn%3Aur.cn%3ASLM%3AERP%3ABusinessData
  url3: ${sap.url}?senderParty=&senderService=SLM_Q&receiverParty=&receiverService=&interface=SLM_MSGResp_Out&interfaceNamespace=urn%3Aur.cn%3ASLM%3AERP%3ABusinessData
