server:
  port: 8087
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
spring:
  application:
    name: eurekaclient
    
management:
  server:
    port: 8087
  endpoints:
    web:
     base-path: /
     exposure:
       include: refresh,health,info #打开部分