server:
  port: 8088
  servlet:
    context-path: /ur-bi-portal
    session:
      cookie:
        name: sessionid_bi_common
        
###eureka配置文件中注明自己的服务注册中心的地址
eureka:
  client:
    ###设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
    serviceUrl:
      defaultZone: http://dev.ims.ur.com.cn:9292/eureka/
    #是否注册
    registerWithEureka: false
  ###配置客户端hostname,statusPageUrlPath为swagger-ui,方便查看接口api
  instance:
    ##本地hostname
    hostname: localhost

spring:
  servlet:
    multipart:
      ##单个数据大小 
      maxFileSize: 5MB
      ##总数据大小
      maxRequestSize: 5MB
  zipkin:
    base-url: http://dev.ims.ur.com.cn:9292
  sleuth:
    sampler:
      ##zipkin采样率，默认为0.1，改为1后全采样，但是会降低接口调用效率
      percentage: 0.1
      #probability: 1.0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxAge: 30000
    #最大空闲时间，30s未使用，则被丢弃
    maxIdleTime: 30
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select '1'
    testWhileIdle: true
    #对数据库连接的有效性进行了验证
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    username: druid
    password: 123456

#    bi-connection:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/ur_bi?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: simon

      bi-connection:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.15.144:3306/imms_dev?useUnicode=true&characterEncoding=UTF-8
        username: usr_CS_admin
        password: baiYezhuiXiong11094

logging:
  level:
    com.ur: DEBUG

cas:
  server:
    host:
      url: http://dev.ims.ur.com.cn:8787/cas            #CAS服务地址  
      login_url: ${cas.server.host.url}/login   #CAS服务登录地址  
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}        #CAS服务登出地址 


######Sense Config Start######
SenseServer: https://qlik.ur.com.cn/hub
UserDirectory: UR_QLIK
Protocol: https
SenseHost: ur-qlik-pp.ur.com.cn
CerPassword: changeit
DefaultUserName:
VirtualProxy:
ErrorPage: ${cas.server.host.login_url}?service=http%3A%2F%2Fcas.ur.com.cn%3A80%2Flogin
######Sense Config End######

#UR企业微信
CORPID: wx015b0a276638b14d
CORPSECRET: KwSj35vxsuQgMymGYGyQYcTToxdTtsBC-Wb8ifaYiAY

#UR资源编码
URRootCode: SENSE-BI

#提供给Sense调用的固定随机码
RANDOMCODE: OI94dBY7pJqMFQ9e


app:
  server:
    host:
      url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}         #应用访问地址
  login:
    url: /login                          #应用登录地址
  logout:
    url: /logout                         #应用登出地址
  tempFilePath: /tmp
  seperator:
  exportPageSize: 50000
  hdfs:
    uri: hdfs://192.168.13.81:8020
    base-path: /ur_bi/
pic:
  server:
    host:
      #scm服务地址
      url: http://192.168.13.38:8383/admin
      #scm文件上传地址
      upload_url: ${pic.server.host.url}/sys/files/upload
      #scm文件下载地址
      download_url: ${pic.server.host.url}/sys/file/handleDownload
      #图片浏览地址，根据abbfilename
      image_url: ${pic.server.host.url}/sys/file/image/
      #http://pic.ur.com.cn/admin/sys/file/cyImageZ/19SY200129_L
      cyImageZ_url: ${pic.server.host.url}/sys/file/cyImageZ/
  
    
    